### ISSUE TITLE
Archive conversations that are older than 14 days

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#334]
**Is your feature request related to a problem? Please describe.**
Currently on the client side we are fetching and listening for changes on all conversations -- even those that were closed month ago. This is starting to slow things down.

Let's add a worker that archives all closed conversations that haven't been updated in over 14 days (2 weeks). This will at least speed things up until we start optimizing our queries (and add pagination, etc).

**Describe the solution you'd like**
We should archive conversations that haven't been updated in 14 days.

* A job should run on a daily basis and archive conversations that haven't been updated in 14 days
  * e.g. `conversation.updated_at` is more than 14 days ago and `conversation.status` is `"closed"`
  * We can use the new `ChatApi.Conversations.archive_conversation` method :) 
* Archived conversations should not show up in the UI anywhere (both in the dashboard and in the chat widget)
  * Edge case would be Slack... maybe we should add a message to the Slack thread that says "this conversation has been archived" or something? (we should probably do that when the conversation is closed as well... I'll set up separate ticket(s) for these issues)

**Additional context**
Archived conversations should not show up anywhere in the UI. For now we should treat them as though they're deleted. The only reason we're not actually deleting them is in case our users need us to restore the data for them.

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by daskycodes** [comment]
I could give this a try and prepare a PR for this full-stack feature.

> Life cycle of a conversation: Open -> Archived -> Deleted (we don't have delete yet)
shouldn't it be Open -> Closed -> Archived -> Deleted?

**Comment by reichert621** [comment]
hey @daskycodes! I think I'd like to break this ticket up into smaller tickets before anyone starts working on this... there's a few things we need to do here:
- we should probably add a `closed_at` field so we known precisely when a conversation was closed
  - for all existing closed conversations, we can just default that field to the current time in the migration
- we'll probably want to add an `archived_at` field as well
- I'm not sure how we should be using the `status` field on the conversation... if we have a `closed_at` and `archived_at` field, it might be a bit redundant to have a `status: "closed"` or `status: "archived"` 🤔 
- we'll need to make sure that the methods that query a list of conversations will **not** include archived conversations
- we'll need to set up a worker than runs every hour(?) that checks if more than 14 days have elapsed since conversations have been closed, and then archives them (by setting `archived_at: DateTime.utc_now()` or something like that)

I don't _think_ there are any frontend changes we need to make for this, but let me know if I'm missing something!

**Comment by daskycodes** [comment]
hey @reichert621 

You are right smaller tasks, will be useful!

- What do you think about using the `:updated_at` field for querying conversations with the `status: "archived"`?
  Since closed conversations won't be updated anymore unless they are reopened this could work.
- Not 100% relevant, but the new `Ecto.Enum` type (Introduced in Ecto 3.5) could be useful to make the schema more readable 
```elixir
field(:status, Ecto.Enum, values: [:open, :closed, :archived], default: :open)
```

**Comment by reichert621** [comment]
@daskycodes yeah I was thinking about using `updated_at` in the meantime, but long term I'd prefer having `closed_at` and `archived_at` because it's helpful to know exactly when these actions occurred

love the idea of using an enum for the `status` field though!

**Comment by reichert621** [comment]
@daskycodes I updated the description of this ticket with more details -- let me know if you're still interested in tackling this!

**Comment by daskycodes** [comment]
@reichert621 I am going to prepare a PR for this in the coming days :) thanks!

**Comment by reichert621** [comment]
thanks @daskycodes! for reference, here's an example of setting up a recurring job:
- The worker itself: https://github.com/papercups-io/papercups/blob/master/lib/workers/example.ex
- Configuring the worker: https://github.com/papercups-io/papercups/blob/master/config/config.exs#L68-L69

**Comment by reichert621** [comment]
done, thanks @daskycodes!
