### ISSUE TITLE
PaperCups.io takes a lot of time to load

### ISSUE THREAD

**Issue by sladyn98** [papercups-io/papercups#377]
The hosted version on Heroku takes a lot of time to come into memory. Have you checked out alternate platforms to deploy the app or any way to make the current hosted version faster? 
My team was planning to deploy a hosted version of papercups but realised it was too slow. CCing my team.

CC @av06 @prem1835

**Comment by cheeseblubber** [comment]
Can you give me more details or send me a gif of the issue with the heroku deploy? We have a docker container where you can run on production for them. I need to add more documentation for it first.

**Comment by cheeseblubber** [comment]
If you are referring to a heroku deploy that takes a while to load. It is because it is deployed to heroku on a free tier which takes time to startup. The way to fix this issue is by upgrading the heroku dynos to a paid version. I think that is the issue https://help.heroku.com/81MBEG7L/how-do-i-upgrade-from-heroku-s-free-tier-and-begin-using-paid-resources 

Going to close the issue for now. Feel free to reopen if this isn't the problem.

**Comment by sladyn98** [comment]
@cheeseblubber Thanks I agree that this is probably the issue. Would love to deploy it on GCP or AWS which would make it much more easier and convenient .
