### ISSUE TITLE
As a CS agent I want to share specific conversation with my team

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#457]
**Problem**
I want to be able to get a link to share with my teammates for specific conversations 

**Solution**
I want to click/copy a link on the context side bar and share that to my team members for that conversation

**Additional context**
Only your teammates can get access to this conversation.

**Comment by cheeseblubber** [comment]
@jamesefhawkins Would the goal of this to be to have the teammate reply to it or is the goal to share a transcript of the conversation?

**Comment by fuziontech** [comment]
I think both. The let's say I spot a question in a conversation that I don't know anything about and want to pass it off to someone who does. It would be super helpful to have a deep link that I could share with them that would take them right to the specific conversation. You do this already in the slack integration including the uuid in the link.

I think the ideal case here is when you click on a conversation you update the url bar with a url that includes uuid of the thread so that you can easily share it with someone else.

**Comment by reichert621** [comment]
@fuziontech should be done in #462 but feel free to reopen if i missed something!
