### ISSUE TITLE
When another agent replies from slack it show up on the left side

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#505]

**Comment by reichert621** [comment]
@cheeseblubber this is somewhat intentional, based on fb messenger where the "current user" always shows up on the right side, and anyone else shows up on the left... I'm curious how Intercom/Drift/etc handle it though 🤔 basically the problem we want to solve is: "it's hard to distinguish between the customer and other agents in the dashboard when multiple agents send messages in a conversation"

should we start off with just showing agents on the right vs customer on the left?
