### ISSUE TITLE
Improve security in `CompanyController` show/update/delete methods

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#641]
**Problem**
Right now any user with a valid auth token can retrieve any `company` resource as long as they know the ID of the resource. We should return a 404 (Not found) error if someone tries to retrieve/update/delete a resource that does not have a matching `account_id`

**Solution**
In the `show`, `update`, and `delete` methods of the company controller, let's add an `authorize` plug (middleware) to handle this.

Check out https://github.com/papercups-io/papercups/pull/639 for an example

**Describe alternatives you've considered**
We could also just include the `account_id` in the query when we fetch the resource 🤷 

**Testing**
Please add/update tests to take these updates into account!

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by ghsyeung** [comment]
Hi, I really like this project :+1: and looking forward to using it at our company.
I have some questions after looking at #639.

First of all I don't have experience in Elixir + Phoenix so please point out if my understanding is incorrect.

My understanding is that `plug` acts like middleware that's called prior to the controller action and the `conn` object should be returned or `halt` should be called (e.g. if the current user doesn't have sufficient privileges to call the controller action.)

In #639, I believe the logic works as follow.

1. a private method `:authorize` is called when the action matches against list
    -  if user is not authorized
       1. a response (404 - Bad Request) is sent back to the user (through the `FallbackController`)
       2. call `halt` to terminate the request

I have some suggestions that may improve security as well as maintainability.

By calling `:authorize` only when an action matches a list, it means actions are **default to open** (i.e. they don't require any authorization). So if someone accidentally forgets to add a protected action to the list, the protected resource would be accessible by anyone.

The alternative approach would be **default to close**. This means the `:authorize` plug is always called. If the action isn't specified, it would fail the request. For example,

```elixir
# not sure if this is the correct syntax
plug Auth.authorize, 
    %{ 
       show: open_to_all, 
       update: can_access_company, 
       delete: can_access_company,       
     }

# this can be defined in the Auth module
def :open_to_all(conn, _) do
    # do nothing, just return `conn`
    conn
end

defp :can_access_company(conn, _) do
    # implement authorization check logic

    # if not authorized, raise an error
    raise "unauthorized"
end
```

where `:authorize` would be a public function from a common module like `Auth`

```elixir
defmodule Auth do
    def authorize(conn, checks) do
        try do 
            check = checks[action_name(conn)]    # check to see if there's authorization check for the action
            unless check do                      # fail if no check specified for the action
                raise "unauthorized"
            end

            check(conn)                          # check whether the user is authorized
       rescue
           _ -> ChatApiWeb.FallbackController.call(conn, {:error, :not_found}) |> halt()
       end
    end
end
```
There are a few benefits to this approach.

1. all API access is default to close
2. authorization logic and error handling inside a common module rather than implemented at all controllers (more maintainable, easier to test) 
3. authorization check methods are easier to write and test (they just raise errors, so there's no dependency on the `FallbackController`)
   - this is important for later on when you need to extend/refine your authorization (e.g. more complex RBAC controls like Admin vs Team Leader vs Staff)

**Comment by a8t** [comment]
We could default to authorize like this:

```diff
- plug :authorize when action in [:show, :update, :delete]
+ plug :authorize when action not in [:index, :create]
```

**Comment by ghsyeung** [comment]
That would work for default to close, but it means each Controller's private `authorize` will need to call `FallbackController`.

But I am not sure how to make it work if a single controller has multiple authorization logic.

For example,

```elixir
%{ 
  update: can_update,  # can only update if owned by current_user
  delete: can_update,   # can only update if owned by current_user
  show: open,
  index: only_admin,    # can only list all if current_user is admin
}
```

The closest I see is something like

```elixir
plug :can_update when action in [:update, :delete]
plug :only_admin when action in [:index]
plug :reject when action not in [:index, :update, :delete]
```

Just sharing this as an idea, it may be the case that there will never be multiple authorization logic within a single controller.

But I also believe that the common pieces of the authorization logic should be in a common module (e.g. currently, there's only 1 line - calling the `FallbackController`). For example, if there's a need to extend the logic to log authorization errors or add telemetry, then you'll only need to modify a single module rather than all controllers.

**Comment by reichert621** [comment]
@ghsyeung thanks for all the thoughts!

just wanted to clarify one thing -- what the `authorize` method is doing at the moment is just checking that the resource being fetched belongs to the same `account_id` as the currently authenticated user; it doesn't mean that the controller endpoint is completely open to any unauthenticated user otherwise (we have another plug that ensures users are authenticated here: https://github.com/papercups-io/papercups/blob/master/lib/chat_api_web/router.ex#L18-L21)

however i do agree that it would be nice to have this be handled by default somehow... i don't think it's too big a deal at the moment since we're not adding new API resources _that_ often (i.e. the current boilerplate doesn't feel _too_ painful), but i agree it'll become a bigger issue when we start introducing more ACLs (or things like that)

in the meantime i wonder if it would make sense to have the plug on by default in each controller, and use pattern matching rather than explicitly list actions to determine when to run it? because i think we basically want to run the plug on any API endpoint with an `:id` in the path, e.g. instead of this...
```elixir
  plug :authorize when action in [:show, :update, :delete]

  defp authorize(conn, _) do
    id = conn.path_params["id"]

    with %{id: user_id, account_id: account_id} <- conn.assigns.current_user,
         message = %{account_id: ^account_id, user_id: ^user_id} <- Messages.get_message!(id) do
      assign(conn, :current_message, message)
    else
      _ -> ChatApiWeb.FallbackController.call(conn, {:error, :not_found}) |> halt()
    end
  end
```
...we could do something like this:
```elixir
  # I'm assuming this will run it for all actions?
  plug :authorize

  # matches on endpoints with an "id" in the path params
  defp authorize(%{path_params: %{"id" => id}} = conn, _) do
    with %{id: user_id, account_id: account_id} <- conn.assigns.current_user,
         message = %{account_id: ^account_id, user_id: ^user_id} <- Messages.get_message!(id) do
      assign(conn, :current_message, message)
    else
      _ -> ChatApiWeb.FallbackController.call(conn, {:error, :not_found}) |> halt()
    end
  end

  # otherwise just passes through
  defp authorize(conn, _), do: conn
```

does that make sense?

**Comment by ghsyeung** [comment]
:+1: I am totally aware that we are talking about authorization, not authentication.

Regarding your idea to run authorization check on matching paths, I don't think it provides much benefit over
running them on `when action in [:show, :update, :delete, :edit]` (the actions with ID if you use [resources](https://hexdocs.pm/phoenix/routing.html#resources)). The code is easier to understand that way.

I agree that authorization should be on by default. The point I want to bring across is whether it's default-open
or default-close.

For example, `Bodyguard` (mentioned in slack) allows you specify a `Catch-all: deny everything else` [policy](https://hexdocs.pm/bodyguard/readme.html#policies) which means it's default-close.

Ultimately, I don't think it'll hurt to common out some parts of the authorization code. Currently each private `:authorize` does the following.

1. for some routes we want to authorize
2. extract parameters from `conn` and load some resource
3. check those against the rules
4. call `FallbackController` if any of the rules aren't satisfied

Point 1 and 4 is the same for all controllers/context, but point 2 and 3 are specific to context/controller/action. I believe `Bodyguard` takes care of 1 and 4 so you can focus on writing 2 and 3 in context/controller. 

This by no means you should adopt `Bodyguard` immediately. You can extract the common logic into a module first, and if you do believe `Bodyguard` is the way to go forward, the code change should be relatively straight forward.

**Comment by a8t** [comment]
Yeah I can do it.

**Comment by a8t** [comment]
Proof of concept is up. I like Bodyguard.

I should note, given above discussion: it's not really 'default open' OR 'default closed'. There's no default. You must write the authorization check into the controller. It's possible to simply not write said line of code. 

The catch-all is for when you _do_ write a line for authorization check, but you specify (via typo for example) a non-existent rule to check against.

**Comment by ghsyeung** [comment]
The PR looks great, I learned quite a bit from it.

_(Big Caveat: I only eyeballed it from the Bodyguard code, never tried it myself)_

Looking at the bodyguard code, if `apply(:authorize)` fails (i.e. none of the guarded `authorize` matches) then `permit` should fail.

https://github.com/schrockwell/bodyguard/blob/develop/lib/bodyguard.ex#L26

https://github.com/schrockwell/bodyguard/blob/develop/lib/bodyguard.ex#L181

So is the catch-all necessary?

Secondly, any insights into why choosing `permit` over the `Plug` approach? (see https://hexdocs.pm/bodyguard/readme.html#plugs).

**Comment by reichert621** [comment]
yeah I kinda like the plug approach, it seems like a nice combination of the recent updates we made with the added benefit of `bodyguard`... what do you think @a8t?

**Comment by a8t** [comment]
I might be wrong, but I can't figure out how to have the Bodyguard.Plug.Authorize plug only run on certain actions.

**Comment by a8t** [comment]
Oh, I think I figured it out. The guard just wasn't happy with the keyword list. I'll push soon.

**Comment by a8t** [comment]
https://github.com/papercups-io/papercups/pull/657/files#diff-38651fc8c71802bee5c5074160f63b5a6ed967c518756f5005d3d948932836e9

Please take a look. I'm... not sure if I like it.
