### ISSUE TITLE
Set up UI for canned responses

### ISSUE THREAD

**Issue by reichert621** [papercups-io/papercups#655]
**Problem**
Now that we have the APIs set up for canned responses, we should build out a simple UI where our users can create/view/edit/delete them :)

**Solution**
Set up a UI! Design TBD, but we can probably use Intercom for inspiration:

<img width="1276" alt="Screen Shot 2021-03-17 at 3 18 18 PM" src="https://user-images.githubusercontent.com/5264279/111525682-3e683d00-8734-11eb-8266-02787c980310.png">

To create a new canned response, we can probably just handle this in a modal with an input for "name" and a textarea for the "content".

(We can also stick with a simpler table UI to start off if that's easier)

**Testing**
Please include a screenshot in your PR.

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by J0** [comment]
Hey!

Can I have this issue?

**Comment by J0** [comment]
Hey,

Due to other commitments, I don't think I've the bandwidth to complete this PR within the next two months. I think I underestimated the load of my other OSS commitments. I'm going to close this PR and unassign my self from this issue so that I don't block anyone from working on this. If there's still no one working on the issue after two months I'll come back to this.

Sorry about this.
