### ISSUE TITLE
Introduce a concept of inboxes

### ISSUE THREAD

**Issue by rhonsby** [papercups-io/papercups#760]
**Problem**
As we add support for multiple channels like SMS, support emails, shared Slack channels, live chats, etc., we need a way to make it easier for users to view conversations based on the channels to better manage them. 

For example, live chats are a bit more time sensitive than channels like SMS, emails, etc. By separating the inboxes and making it easy to see which ones have unread messages, users can more easily manage which ones they reply to. 

In the future, we'll also want users to be able to create multiple inboxes that use the same channels. For example, a user might have two chat widgets, one on the landing page and one in their app, which should direct messages to two different live chat inboxes. 

**Solution**
Our goal is to have a separate inbox per channel. For the v0 implementation, I want to do the simplest thing possible:

### Frontend
* Create a submenu in the navigation that with menu items for each channel (e.g. email, slack, chat). Instead of `/conversations/all`, we'll follow a format of `/conversations/<source>` (e.g. `/conversations/slack`, `/conversations/email`, `/conversations/chat`). 
* Re-use the `ConversationDashboard` component used for `/conversations/all`, extend it to accept the `source`, and pass the `source` value to the server when querying for conversations.

### Backend
* Update `conversation_controller.ex#index` to make use of the `source` to filter the results.

**Describe alternatives you've considered**
No other alternatives considered, but open to suggestions.

**Testing**
This will be tested by creating multiple conversations with varying sources, navigating to each inbox, and verifying that the conversations are rendered in the correct inboxes.

**Questions, or need help getting started?**
Feel free to ask below, or [ping us on Slack](https://join.slack.com/t/papercups-io/shared_invite/zt-h0c3fxmd-hZi1Zp8~D61S6GD16aMqmg) :)

(You can also check out our [CONTRIBUTING.md](https://github.com/papercups-io/papercups/blob/master/CONTRIBUTING.md))

**Comment by reichert621** [comment]
@rhonsby this seems great! i'm assuming that once conversations are closed from these new inboxes, they just go to the "Closed" section of the primary inbox?

seems like a good first step :+1: eventually we'll need a concept of an `inbox` model but for now having these "filters by channel" will be helpful for us

**Comment by rhonsby** [comment]
@reichert621 

> once conversations are closed from these new inboxes, they just go to the "Closed" section of the primary inbox?

Yeah, that's basically what would happen since the "inboxes" right now are really just filters on the source. 

> eventually we'll need a concept of an inbox model

Can you expand on this? How do you imagine inboxes to work in the future?

**Comment by reichert621** [comment]
one easy example that a few people have asked for is having an "inbox" for their landing page and then a separate "inbox" for their dashboard -- e.g. they would pass in an inbox ID/name into their chat config and that would ensure that conversations from that chat widget are passed to the correct inbox (or have some inbox logic that says "if customer messages from this URL, send to inbox B; otherwise send to inbox A)

another example could just be where an inbox represents a group of conversations based on a pre-defined filter, where you can assign certain conversations to an inbox based on tags/keywords/etc (i think this is what "inboxes" are in front/chatwoot/etc 🤔 )

i think for now just being able to filter by source will be nice, but curious what kam thinks is most important after that (cc @cheeseblubber) all i know is that some point we'll want to make it possible for users to create/manage inboxes on their own
