### ISSUE TITLE
Customer API endpoint doesn't update metadata

### ISSUE THREAD

**Issue by CharlesMangwa** [papercups-io/papercups#995]
**Describe the bug**
After following the docs to update a customer, the metadata is always returned as `null`.

**To Reproduce**
1. Create an API key in the dashboard
2. Add your API key as a `Bearer` token & make a `GET` request to retrieve any customer `id` via `https://app.papercups.io/api/v1/customers/`
2. With that `id`, make a `PUT` request to `https://app.papercups.io/api/v1/customers/[id]/` with a body, ie:
```JSON
{
   "customer":{
      "metadata":{
         "random_custom_field":"034c0f85-0be3-4086-acf8-85ed8f4f1228"
      }
   }
}
```
3. You get a `200` but `data.metadata` is still `null`

**Expected behavior**
`data.metadata` would return the provided `"random_custom_field": "034c0f85-0be3-4086-acf8-85ed8f4f1228",`.

**Comment by jeepers3327** [comment]
I believe you should use PUT request on  `https://app.papercups.io/api/v1/customers/[id]/metadata` as described in the `router.ex` file https://github.com/papercups-io/papercups/blob/7c850c47ff244dbdc03fa1fa5e28011b2f338653/lib/chat_api_web/router.ex#L52

The reason `https://app.papercups.io/api/v1/customers/[id]/` returns a null is because the changeset used in `update_customer` does not pick up the `metadata` key.
https://github.com/papercups-io/papercups/blob/7c850c47ff244dbdc03fa1fa5e28011b2f338653/lib/chat_api/customers.ex#L254-L258
https://github.com/papercups-io/papercups/blob/7c850c47ff244dbdc03fa1fa5e28011b2f338653/lib/chat_api/customers/customer.ex#L91-L119

But when you look at changeset used in `Customers.update_customer_metadata` it picks up the `metadata` key.
https://github.com/papercups-io/papercups/blob/7c850c47ff244dbdc03fa1fa5e28011b2f338653/lib/chat_api/customers/customer.ex#L121-L143

**Comment by CharlesMangwa** [comment]
Thanks for the lead @jeepers3327! I forgot to mention in my initial description that I _did_ try a `PUT` on `https://app.papercups.io/api/v1/customers/[id]/metadata` but it returns 
```
{
  "errors": {
    "detail": "Not Found"
  }
}
```
even though the `id` I provided does exist and all. Am I missing something obvious?

FWIW: I also tried `https://app.papercups.io/api/customers/[id]/metadata` (without the `v1`). This one does return the `data` object but `metadata` is still `null`.

**Comment by jeepers3327** [comment]
Hi @CharlesMangwa,
Could you try accessing this endpoint `` with your `id` and tell me the result if it exist or not. Based on https://github.com/papercups-io/papercups/blob/master/lib/chat_api_web/router.ex, it shouldn't matter whether there's a `v1` prefix on the api endpoint or not.

Note: I don't really launch the application on my local or the hosted version, I just give out advice based on the code.

**Comment by CharlesMangwa** [comment]
hey @jeepers3327, thanks for your help, it's much appreciated!

There seem to be different scopes actually:

https://github.com/papercups-io/papercups/blob/1ad023a1a5e3bdb915ff4c8790ea149439d08e9a/lib/chat_api_web/router.ex#L35

https://github.com/papercups-io/papercups/blob/1ad023a1a5e3bdb915ff4c8790ea149439d08e9a/lib/chat_api_web/router.ex#L182

 with only the former accepting `put("/customers/:id/metadata")`:

https://github.com/papercups-io/papercups/blob/1ad023a1a5e3bdb915ff4c8790ea149439d08e9a/lib/chat_api_web/router.ex#L52

That could explain why trying to access `/api/v1/customers/[id]/exists` only opens up the Papercups dashboard but `/api/customers/[id]/exists` does return 
```
{
  "data": true
}
```
as `/exists` is defined in the `/api` scope only:

https://github.com/papercups-io/papercups/blob/1ad023a1a5e3bdb915ff4c8790ea149439d08e9a/lib/chat_api_web/router.ex#L51

**Comment by jeepers3327** [comment]
Have you checked if metadata field was filled when you update it or does it nullify the current metadata value

**Comment by CharlesMangwa** [comment]
There's no metadata (`null`) and I'm trying to add some but it always returns `null`

**Comment by jeepers3327** [comment]
Hi @CharlesMangwa,

I've found the bug and how to fix it, though I need to ask for confirmation from @reichert621 regarding the fix. 


From line 131 - 142, it fetches `metadata` from the `PUT` request, merges it with extra fields and then transform some of fields after sanitizing it. https://github.com/papercups-io/papercups/blob/7c850c47ff244dbdc03fa1fa5e28011b2f338653/lib/chat_api_web/controllers/customer_controller.ex#L127-L144

Based from the line map transformation the given map below (came from PUT request):
```
{
    "metadata": {
        "social handle": "mikoto"
    }
}
```
will become
```
%{
  "ip" => nil,
  "last_seen_at" => ~U[2021-12-04 11:11:38.308617Z],
  "social handle" => "mikoto"
}
```
and since updating a metadata calls `Customers.update_customer_metadata` function, the `Customer.metadata_changeset` will also be called, processing the merged map. Now, since `metadata` key is no longer present upon calling the changeset it becomes null https://github.com/papercups-io/papercups/blob/7c850c47ff244dbdc03fa1fa5e28011b2f338653/lib/chat_api/customers/customer.ex#L121-L142

## Fix

The fix is actually simple, instead of https://github.com/papercups-io/papercups/blob/7c850c47ff244dbdc03fa1fa5e28011b2f338653/lib/chat_api/customers.ex#L284-L290
I make it like this

```
  def sanitize_metadata(metadata) do
    metadata
    |> sanitize_metadata_email()
    |> sanitize_metadata_external_id()
    |> sanitize_metadata_current_url()
    |> sanitize_ad_hoc_metadata()
    |> prepare_metadata()
  end

  def prepare_metadata(metadata) when is_map(metadata), do: %{metadata: metadata}
  def prepare_metadata(metadata), do: metadata
```

After applying the change, here's what Ecto.Changeset prints out.
```
#Ecto.Changeset<
  action: nil,
  changes: %{
    metadata: %{
      "ip" => nil,
      "last_seen_at" => ~U[2021-12-04 11:18:05.094519Z],
      "social handle" => "mikoto"
    }
  },
  errors: [],
  data: #ChatApi.Customers.Customer<>,
  v
```

**Comment by reichert621** [comment]
hey @jeepers3327 thanks for all the help on this! would you mind putting up a PR with your fix? 😄

**Comment by CharlesMangwa** [comment]
Hey @jeepers3327! Do you think you could put up a PR with this fix pls?

**Comment by CharlesMangwa** [comment]
Closed by https://github.com/papercups-io/papercups/pull/1000#issuecomment-1122855148.
